module.exports = {
  PORT: process.env.PORT,
  DB_CONNECTION_URL: process.env.DB_CONNECTION_URL,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET || 'Secret',
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET || 'SuperSecret',
  REGISTRY_TOKEN_SECRET: 'dpdpfmkckcdc' || 'Secret',
  FORGOT_TOKEN_SECRET: 'dpdpfmkckcdc' || 'Secret',
  AUTHORIZATION: 'Authorization',
  REGISTRY_TOKEN_TIME: '10m',
  FORGOT_TOKEN_TIME: '10m',
  ACCESS_TOKEN_TIME: '10m',
  REFRESH_TOKEN_TIME: '30d',
  ACCESS: 'access',
  REFRESH: 'refresh',
  EMAIL: process.env.EMAIL,
  PASSWORD: process.env.PASSWORD,
  USERS: 'users',
  AVATAR: 'avatar',
  PHOTO: 'photo'
};
